---
mirte_speed_control:
  p: 1
  i: 0
  d: 0
  i_clamp: 50
  antiwindup: true
# ekf_localization:
#   frequency: 50
#   two_d_mode: true
#   odom0: /ridgeback_velocity_controller/odom
#   odom0_config: [false, false, false,
#                  false, false, false,
#                  true, true, false,
#                  false, false, true,
#                  false, false, false]
#   odom0_differential: false
#   imu0: /imu/data
#   imu0_config: [false, false, false,
#                 false, false, false,
#                 false, false, false,
#                 false, false, true,
#                 true, true, false]
#   imu0_differential: false
#   odom_frame: odom
#   base_link_frame: base_link
#   world_frame: odom
#   predict_to_current_time: true
