/**:
  ros__parameters:
    device:
      mirte:
        type: pcb
        version: 0.6
        max_frequency: 50
    # modules:
      # motorservocontroller:
      #   device: mirte
      #   type: PCA9685
      #   addr: 0x41
      #   connector: I2C1
      #   frequency: 100
      #   motors: # TODO: No Idea which motor configuration is correct.
      #     rear_left:
      #       pin_A: 6 #0
      #       pin_B: 7 #1
      #     front_left:
      #       pin_A: 2
      #       pin_B: 3
      #     rear_right:
      #       pin_A: 5
      #       pin_B: 4
      #     front_right:
      #       pin_A: 1
      #       pin_B: 0
      # servo_controller:
      #   device: mirte
      #   type: Hiwonder_Servo
      #   pins:
      #     rx: 0
      #     tx: 1
      #   servos:
      #     shoulder_pan:
      #       id: 2
      #       home_out: 12000
      #       min_angle_out: 3400
      #       max_angle_out: 21000
      #       invert: false
      #     shoulder_lift:
      #       id: 3
      #       home_out: 11450
      #       min_angle_out: 2832
      #       max_angle_out: 20000
      #       invert: false
      #     elbow:
      #       id: 4
      #       home_out: 11750
      #       min_angle_out: 120
      #       max_angle_out: 21000
      #       invert: false
      #     wrist:
      #       id: 5
      #       home_out: 12200
      #       min_angle_out: 1128
      #       max_angle_out: 21000
      #       invert: false
      #     gripper:
      #       id: 6
      #       home_out: 10524
      #       min_angle_out: 6168
      #       max_angle_out: 14224
      #       invert: false
      # power_watcher:
      #   device: mirte
      #   type: INA226
      #   pins:
      #     scl: 15
      #     sda: 14
      #   addr: 0x40
      #   min_voltage: 11.1
      #   max_current: 5
      #   max_voltage: 15
      #   turn_off_time: 10
      #   power_low_time: 20.0
      #   percentage_led_pin: GPIO4_B4 # 12 = B4, left-most led on usb switcher pcb
      # movement:
      #   device: mirte
      #   type: MPU9250
      #   connector: I2C1
    encoder:
      front_left:
        name: front_left
        device: mirte
        pins:
          B: 4
          A: 5
      rear_left:
        name: rear_left
        device: mirte
        pins:
          B: 8 #11
          A: 9 #12
      rear_right:
        name: rear_right
        device: mirte
        pins:
          A: 18 #24
          B: 19 #25
      front_right:
        name: front_right
        device: mirte
        pins:
          B: 22 #29
          A: 26 #31
    motor:
      front_left:
        name: front_left
        device: mirte
        invert: true
        type: pp
        pins:
          p1: 2
          p2: 3
      rear_left:
        name: rear_left
        device: mirte
        invert: false
        type: pp
        pins:
          p1: 6
          p2: 7
      front_right:
        name: front_right
        device: mirte
        invert: false
        type: pp
        pins:
          p1: 28
          p2: 27
      rear_right:
        name: rear_right
        device: mirte
        invert: false
        type: pp
        pins:
          p1: 21
          p2: 20
    distance:
      front_left:
        name: front_left
        device: mirte
        frame_id: front_left_sonar
        pins:
          trigger: 17
          echo: 16
      # rear_left:
      #   name: rear_left
      #   device: mirte
      #   frame_id: rear_left_sonar
      #   pins:
      #     trigger: 8
      #     echo: 9
      front_right:
        name: front_right
        device: mirte
        frame_id: front_right_sonar
        pins:
          trigger: 17
          echo: 13
      # rear_right:
      #   name: rear_right
      #   device: mirte
      #   frame_id: rear_right_sonar
      #   pins:
      #     trigger: 12
      #     echo: 13
    oled:
      oled:
        device: mirte
        pins:
          scl: 15
          sda: 14
