/**:
  ros__parameters:
    device:
      mirte:
        type: pcb
        version: 0.8
        board: pico
        max_frequency: 50
    modules:
      motorservocontroller:
        device: mirte
        type: PCA9685
        addr: 0x40
        connector: I2C1
        frequency: 50
        servos: # TODO: No Idea which motor configuration is correct. Test
          gas:
            pin: 1 #0
          stuur:
            pin: 0 #1
            # pin_B: 7 #1
          # front_left:
          #   pin_A: 2
          #   pin_B: 3
          # rear_right:
          #   pin_A: 5
          #   pin_B: 4
          # front_right:
          #   pin_A: 1
          #   pin_B: 0
