# bloom-generate rosdebian
# fakeroot debian/rules binary

on: [push]
permissions:
  contents: write
jobs:
  build_testing:
    runs-on: ubuntu-latest
    strategy:
        matrix:
                ros_distro: [humble]
                deb_distro: [jammy]
                arch: [amd64, armhf]
        fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: arendjan/ros-deb-builder-action@main
        with:
          ROS_DISTRO: ${{ matrix.ros_distro }}
          DEB_DISTRO: ${{ matrix.deb_distro }}
          DEB_ARCH: ${{ matrix.arch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ROSDEP_SOURCE: yaml file:///home/runner/work/mirte-ros-packages/mirte-ros-packages/rosdep.yaml debian
          REPOS_FILE: ./ros2_sources.repos
          SKIP_CHECKOUT: true
          

