# bloom-generate rosdebian
# fakeroot debian/rules binary

on: [push]
jobs:
  build_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: self-checkout
        run: |
             mkdir src
             mv ./mirte_* ./src
      - uses: jspricke/ros-deb-builder-action@main
        with:
          ROS_DISTRO: humble
          DEB_DISTRO: jammy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_CHECKOUT: true

