name: Catkin_lint ros style check
on: [push, pull_request]
jobs:
  check_ros_style:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic
    steps:
      - uses: actions/checkout@v3
      - run: echo "catkin_lint" > ./requirements.txt
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.9'
      #     cache: 'pip' # caching pip dependencies
      # - run: apt install python-pip
      - run: apt update && apt install catkin-lint -y
      - run: |
          mkdir -p catkin_ws/src
          mv mirte_bringup catkin_ws/src/
          mv mirte_control catkin_ws/src/
          mv mirte_msgs catkin_ws/src/
          mv mirte_telemetrix catkin_ws/src/
          mv mirte_teleop catkin_ws/src/
          cd catkin_ws/src
          . /opt/ros/noetic/setup.sh
          catkin_init_workspace
          cd ..
          rosdep init || true
          rosdep update || true
          rosdep install -y --from-paths src/ --ignore-src --rosdistro noetic
          catkin_make
          . devel/setup.sh
      - run: |
          . catkin_ws/devel/setup.sh
          failure=0
          catkin_lint --explain --ignore uninstalled_target --pkg mirte_bringup || failure=1
          catkin_lint --explain --ignore uninstalled_target --pkg mirte_control || failure=1
          catkin_lint --explain --ignore uninstalled_target --pkg mirte_msgs || failure=1
          catkin_lint --explain --ignore uninstalled_target --pkg mirte_telemetrix || failure=1
          catkin_lint --explain --ignore uninstalled_target --pkg mirte_teleop || failure=1
          if failure; then
              echo "Automated tests failed" >&2
          exit 1
          else
              echo "Automated tests succeeded" >&2
              exit 0
          fi

